### ISSUE TITLE
Basic User Get by Username API Call not working 

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#110]
![selection_006](https://cloud.githubusercontent.com/assets/21987154/24891621/0f9d7f64-1e45-11e7-8061-2514b9818ab1.png)
![selection_007](https://cloud.githubusercontent.com/assets/21987154/24891622/118d637a-1e45-11e7-8ba2-b06c082a4256.png)

I'm attempting to do the "View user Profile" use cases, but I need this api end point to work.

**Comment by fredlo2010** [comment]
@hchev001 I am not able to replicate your problem.
 Follow the instructions to make sure you are in synch 

1. Make sure you have the latest version from master
2. Run the start.sh script to make sure front and backend are build correctly
3. Run the start.sql to make sure the database is in synch
4. Try again 

![image](https://cloud.githubusercontent.com/assets/10730107/24910629/53f4e480-1e96-11e7-8b7c-d2590ec8df09.png)

**Comment by hchev001** [comment]
Neither can I replicate the bug I had yesterday lol, thanks for the fix :-)

Hamilton Chevez
hamiltonchevez.com
(954) 918-8527

**Comment by fredlo2010** [comment]
I will close it for now if we see it again we will reopen.
