### ISSUE TITLE
I need /api/search is missing username field.

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#123]
So I'm trying to implement "search", that is to be able to search for a business given a string query. 
From the Search-View where a list of business entity page profiles get populated, to go to each business entity page we click on their name or picture and I use their username to fetch the business entity page data via GET /api/business/{username}. However, if I use POST /api/search to populate the list of business entity pages in the Search View, that api endpoint doesn't return a username field.

Could you please add the username field to the data response of the POST /api/search end point please.
The search use case works right now, but its breaking the View Business Entity Page use case.

**Comment by fredlo2010** [comment]
This has been fixed
