### ISSUE TITLE
Broken FrontEnd Mock Authorization

### ISSUE THREAD

**Issue by fredlo2010** [hchev001/UniPS#49]
The frontEnd build breaks throwing the following error:

<pre>
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 7:17 in the original .ts file), resolving symbol fakeBackendProvider in C:/Users/alfredo/Github/UniPS/frontEnd/src/app/_helpers/fake-backend.ts, resolving symbol AppModule in C:/Users/alfredo/Github/UniPS/frontEnd/src/app/app.module.ts, resolving symbol AppModule in C:/Users/alfredo/Github/UniPS/frontEnd/src/app/app.module.ts
</pre>

To replicate:

1. Go to directory **UniPS/frontEnd**
2. Execute from the terminal **ng build**

I think this was added to mock authentication. We already have an API fr that in backend. And to wire it up I think we only need this piece of code (This is Angular 1, needs to be translated to Angular 2)
Use the link as a reference.

https://spring.io/guides/tutorials/spring-security-and-angular-js/#_modular_angular_js_and_spring_security_part_vii

````javascript
 authenticate : function(credentials, callback) {

          var headers = credentials && credentials.username ? {
            authorization : "Basic "
                + btoa(credentials.username + ":"
                    + credentials.password)
          } : {};

          $http.get('user', {
            headers : headers
          }).then(function(response) {
            if (response.data.name) {
              auth.authenticated = true;
            } else {
              auth.authenticated = false;
            }
            $location.path(auth.homePath);
            callback && callback(auth.authenticated);
          }, function() {
            auth.authenticated = false;
            callback && callback(false);
          });
````
@hchev001 @mebra005

**Comment by hchev001** [comment]
Yeah this is an error relate to Milad's login stuff

**Comment by mebra005** [comment]
I deactivate the back-end for now. For any reason, if you want to try the backend:

1. ng serve
2. take off the comment symbols from the following files
3. save the files.

- src/_helpers/fake-backend.ts 
- src/_helpers/index.ts
- /src/app.modules

**Comment by hchev001** [comment]
This no longer exist or is being used so I'm closing this issue
