### ISSUE TITLE
Update SQL Business Descriptions

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#82]
The Business Descriptions need to be updated to something beyond "I am Chillis". For example Chili's could be "A tex-mex style restaurant, home of the famous baby back ribs and the Monterey chicken." or we can look up the actual slogan or description from their website.

**Comment by DSchiumerini** [comment]
Do you mean 

A) in the start.sql file under

> -- ------------------------ --
-- Populate all tables needed --
-- ------------------------ --
>-- and data for business
INSERT INTO `unipsdb`.`user`
	(`username`, `password`, `name`, `phone`, `phone_business`, `email`, `question1`, `question2`, `description`, `hours`, `address_id`, `status_id`, `role_id`, `business_category_id`)
VALUES
	('chillis', '5b3a02c900752a8a70f157ce633d37561d6a89cb', 'Chillis', 3053482668, 3053482668, 'chillis@chillis.com', 'chillis answer 1', 'chillis answer 2', **_'I am Chillis'_**, '11AM - 10PM', 1, 1, 2, 0), 


or 

B) did you want me to upload a specific query that allows a Business User to update his/her description?

If A, those values are just temporary the real database will have more accurate values for every table.

**Comment by fredlo2010** [comment]
This has been fixed now. To reflect the changes in the local Database just run "start.sql" from MyWorkbench
