### ISSUE TITLE
URGENT: can't register a new user/business

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#91]
So I've noticed a bug when trying to make a post request to register a new user via /api/users. It requests via a pop up to log in, because localhost:8080 requires authentication. If I try kathy k123 it works but it doesn't make sense why I'm getting back an Unauthorized 401 status code when trying to register. I'm wondering now also why 403 Forbidden status code also applies to /api/users. These same status codes exist for /api/business. 

Guests should be allowed to register for an account without having to input these credentials.

![selection_011](https://cloud.githubusercontent.com/assets/21987154/24831598/b97c6ac2-1c6a-11e7-97c1-72188f9188cd.png)

![selection_013](https://cloud.githubusercontent.com/assets/21987154/24831592/aa9bdd76-1c6a-11e7-8a12-21d363b3b13d.png)
![selection_012](https://cloud.githubusercontent.com/assets/21987154/24831593/ac7afe56-1c6a-11e7-8814-c26156ddba9b.png)

**Comment by fredlo2010** [comment]
This has been fixed. Please use the new set of API's destined to access the public information. 

![image](https://cloud.githubusercontent.com/assets/10730107/24831874/dadab38a-1c70-11e7-941f-58b49496ebcd.png)
