### ISSUE TITLE
EMAIL Service: Invalid Addresses Spring Boot Exception

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#93]
I'm testing the register feature of our application. Registering a user and verifying via email works, and then logging in with the user works too. However, an exception occurs in the background something regarding the email service.
To recreate this bug just checkout the registrationUseCase branch, build the project and whatnot, register for a new user account then check eclipse.
![selection_004](https://cloud.githubusercontent.com/assets/21987154/24832895/91f2913e-1c88-11e7-97b8-93585661f3fe.png)

**Comment by fredlo2010** [comment]
@hchev001 This is because 'hamilton3' is not a valid email address. 

To avoid issues like this user the inputs from 
https://docs.angularjs.org/api/ng/input/input%5Bemail%5D

They will catch any error or validation problems. So neither you nor I have to do validation. 👍

**Comment by hchev001** [comment]
yeah that may have been my mistake, I'll close it now
