### ISSUE TITLE
EMAIL Service: Verification link new window

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#94]
Upon registering for a new account, the new user receives an email to verify their account before using it. The email contains a link that opens up a new browser and displays this image, what appears to be a JSON object.  This behavior occurs for both new user and business registrations.
![selection_003](https://cloud.githubusercontent.com/assets/21987154/24832935/84f69ef2-1c89-11e7-9e53-78387bace5e8.png)

**Comment by fredlo2010** [comment]
This is valid. And actually an very good email. It means that the user has been correctly matched to the token.

Now, for the business we are not done yet. We the admins should get another email to approve the new business (I do not see it, investigating now)

**Comment by fredlo2010** [comment]
This has been fixed and merged with master
